---
title: "オリジナルからtidyデータへの変換"
output: rmarkdown::html_vignette
author: Vintea
date: 01/17/2020
vignette: >
  %\VignetteIndexEntry{article01_tidying}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
knitr::opts_knit$set(root.dir = "./")
```

```{r setup}
library(openNDB)
```

## 処方薬

### 性年齢別

```{r eval=FALSE}
for (xlsx in list.files("../NDBdata/original/syohouyaku/sex_age/")){
  df_tidy <- tidy_syohouyaku_sex_age(paste("../NDBdata/original/syohouyaku/sex_age/", xlsx, sep = ""))
  arrow::write_parquet(df_tidy, paste("../NDBdata/apache/syohouyaku/sex_age/", substr(xlsx, start = 1, stop = nchar(xlsx)-4), 
                              "parquet", sep = ""))
  write.csv(df_tidy, paste("../NDBdata/csv/syohouyaku/sex_age/", substr(xlsx, start = 1, stop = nchar(xlsx)-4), 
                              "csv", sep = ""))
}
```

### 都道府県別

```{r eval=FALSE}
for (xlsx in list.files("../NDBdata/original/syohouyaku/prefecture/")){
  df_tidy <- tidy_syohouyaku_prefecture(paste("../NDBdata/original/syohouyaku/prefecture/", xlsx, sep = ""))
  arrow::write_parquet(df_tidy, paste("../NDBdata/apache/syohouyaku/prefecture/", substr(xlsx, start = 1, stop = nchar(xlsx)-4), 
                              "parquet", sep = ""))
  write.csv(df_tidy, paste("../NDBdata/csv/syohouyaku/prefecture/", substr(xlsx, start = 1, stop = nchar(xlsx)-4), 
                              "csv", sep = ""))
}
```




