---
title: "Example 1: 男女で使用割合が大きく異なる薬剤"
author: "Vintea"
date: "1/15/2020"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{openNDB}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "./")
library(tidyverse)
```

## 概要

### 元データ

第4回NDBオープンデータから「外来（院外）性年齢別薬効分類別数量」

### リサーチクエスチョン

性差によって使用数が大きく異なる薬剤はなんだろうか？

## import

```{r}
library(openNDB)
data <- suppressMessages(tidy_syohouyaku_sex_age("../NDBdata/original/syohouyaku/内服_外来_院外_性年齢別.xlsx"))

# or load parquet file
# data <- read_parquet("../NDBdata/apache/syohouyaku/内服_外来_院外_性年齢別.parquet")

head(data)
```

## transform

差だと処方回数の多い薬剤が有利になるので割合をみる。なおn/0=Inf, 0/0=NaNとなる。今回はともに0となる場合は性差はないので気にしなくていい。

```{r}
data_trans <- data %>% select(drugname, sex, count) %>% 
  mutate(sex=factor(sex, levels = c(0,1), labels=c("male","female"))) %>% 
  group_by(drugname, sex) %>% 
  summarise(sum(count, na.rm = TRUE)) %>% 
  pivot_wider(names_from = sex, values_from = 3) %>% 
  mutate(diff_by_sex = female/male)

head(data_trans)
```

## result

### 男性だけが使っている薬剤

```{r}
data_trans %>% filter(diff_by_sex==0)
```

135薬剤が該当した。

### 女性も使っているが男性が多い薬剤

```{r}
data_trans %>% filter(diff_by_sex!=0) %>% arrange(diff_by_sex)
```

### 男性も使っているが女性が多い薬剤

```{r}
data_trans %>% filter(diff_by_sex!=Inf) %>% arrange(desc(diff_by_sex))
```

### 女性だけが使っている薬剤

```{r}
data_trans %>% filter(diff_by_sex==Inf)
```

121薬剤が該当した。
